#Makefile
#Drake Wheeler

CC = gcc
DEBUG = -g -DNOISY_DEBUG
CFLAGS =  -Wall -Wextra -Wshadow -Wunreachable-code -Wredundant-decls -Wmissing-declarations -Wold-style-definition \
		 -Wmissing-prototypes -Wdeclaration-after-statement -Wno-return-local-addr -Wunsafe-loop-optimizations \
		 -Wuninitialized -Werror

PROG1 = psush
PROGS = $(PROG1)

#source files for the project
SRCS = psush.c cmd_parse.c
#object files for each source file, automatically generated by replacing .c with .o
OBJS = $(SRCS:.c=.o)

all: $(PROGS)

$(PROG1): $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

# Explicit compilation rules for each source file
psush.o: psush.c
	$(CC) $(CFLAGS) -c psush.c -o psush.o

cmd_parse.o: cmd_parse.c
	$(CC) $(CFLAGS) -c cmd_parse.c -o cmd_parse.o

#adds -g for debug compile and -DNOISY_DEBUG to the compile flags for program to define the macro at compile time
#and print out the debug statements while the program is running
debug: CFLAGS += $(DEBUG)
debug: all

clean cls:
	rm -f $(PROGS) *.o *~ \#*
